### ISSUE TITLE
大神请教你一个问题

### ISSUE THREAD

**Issue by rmtic** [goldze/MVVMHabit#11]
SubmitTransitionButton一个view控件，有onSuccess()和onFailure()这两个方法(xml是没有属性可以调用这两个方法。只能在代码里面调用).
请问如果我用mvvmHabit 我要怎么控制，可以写个例子吗，还有怎么获取获取页面的view 例如 binding.mainTv1.setText();

**Comment by goldze** [comment]
参考官方databinding自定义BindingAdapter，来回调onSuccess()和onFailure()。
在xml定义好好id, 直接使用binding.id名就可以找到页面View
