### ISSUE TITLE
大神你写的太好了

### ISSUE THREAD

**Issue by rmtic** [goldze/MVVMHabit#12]
大神你写的太好了，我经过一段时间的编写，发现你封装很细，完全可以用到项目上

**Comment by goldze** [comment]
谢谢支持！

**Comment by goldze** [comment]
@rmtic 如果你看懂登录界面的话, 这个很简单, 在UIChangeObservable中定义一个观察者, 在Fragment中注册监听就好了，为什么不写全, 原因就是不可能所有人都用这个下拉刷新控件的, 这里只是一个例子, 当你知道事件回调后, 执行了 ToastUtils.showShort("下拉刷新");  剩下的操作你想怎么干就是自己项目的业务逻辑了

**Comment by rmtic** [comment]
好的，谢谢你！

**Comment by ppoodao** [comment]
ExceptionHandle 这个类咋用用
