### ISSUE TITLE
扩展问题

### ISSUE THREAD

**Issue by yinguanping** [goldze/MVVMHabit#15]
请教博主：
1.如果RecyclerView如果绑定的item是多种样式的怎么使用ItemBinding<NetWorkItemViewModel> 模式在xml进行itemBinding呢。这里默认的itemBinding都是传一个R.layout.xx的布局进去，那多个布局样式的呢？
2.怎么支持扩展呢，比如MD的BottomNavigationView控件怎么封装在xml直接使用binding的方式绑定数据呢，而且有可能是服务器返回的动态tab的绑定信息

跪求博主回复，现在对databinding还是小白。但是很希望把这个框架用起来

**Comment by goldze** [comment]
@yinguanping 
1、RecyclerView的更多绑定方式可以看这个:https://github.com/evant/binding-collection-adapter
2、如果你真的想把这个框架用起来就多学一下Databinding
