### ISSUE TITLE
ContainerActivity返回到指定的ContainerActivity

### ISSUE THREAD

**Issue by lql7993259lql** [goldze/MVVMHabit#17]
当使用startContainerActivity多次来跳转ContainerActivity的时候，这时候要跳转到指定的某个fragment，怎么操作，望大神指教。谢谢

**Comment by goldze** [comment]
@lql7993259lql 没太看明白你的问题，你题目是返回到指定ContainerActivity，内容却又是跳转到某个fragment，跳转和返回是两种完全相反的意思，请重新描述一下你的问题。

**Comment by lql7993259lql** [comment]
@goldze ContainerActivity里面都是fragment,当使用startContainerActivity依次启动A,B,C,D,E五个ContainerActivity的时候，这时想让E回退到B，相当于要CDE出栈。只剩下AB。

**Comment by goldze** [comment]
@lql7993259lql 方法有很多种，1、在这样一个场景下做一个临时的堆栈管理Activity，当需要从E进入B时, 从堆栈中取出CDE关闭，2、B界面不用ContainerActivity，用普通的Activty设置singletask模式，从E跳转到B则自动会关闭CDE，3、通过事件总线，CDE注册关闭的监听，当E需要跳入B时发送事件，CDE收到后自然就关闭了。这里列举常用的三种，具体还需要根据场景来。
