### ISSUE TITLE
使用的方法有误，应该是执行： onScrollStateChangedCommand.execute(Integer.valueOf(scrollState))；才对？

### ISSUE THREAD

**Issue by jiangwenzhong** [goldze/MVVMHabit#25]
https://github.com/goldze/MVVMHabit/blob/89ada4af0c5a725ea3763c50a1322afd11ad31ec/mvvmhabit/src/main/java/me/goldze/mvvmhabit/binding/viewadapter/recyclerview/ViewAdapter.java#L44

**Comment by goldze** [comment]
@jiangwenzhong  谢谢反馈, 已修正

**Comment by jiangwenzhong** [comment]
listview的viewAdapter也是一样的错误
