### ISSUE TITLE
网络请求带空的HashMap,Printer会报错

### ISSUE THREAD

**Issue by tinybright** [goldze/MVVMHabit#37]
![image](https://user-images.githubusercontent.com/8720949/48200619-b1aa5900-e39a-11e8-972e-9886f4a3f18e.png)

**Comment by goldze** [comment]
@tinybright 感谢反馈! 错误能给详细点吗？是怎么导致的, 出现了什么异常？我这边试了好几种请求方式都无法还原你说的问题

**Comment by tinybright** [comment]
@goldze 
![1](https://user-images.githubusercontent.com/8720949/48261486-35774a80-e45a-11e8-8a29-295a24d6619c.png)
![2](https://user-images.githubusercontent.com/8720949/48261487-37d9a480-e45a-11e8-9f93-729a596a2e38.png)

**Comment by tinybright** [comment]
@goldze 
![image](https://user-images.githubusercontent.com/8720949/48261673-cc440700-e45a-11e8-96bf-a35aa3763919.png)
这个加分割线的也有bug

**Comment by goldze** [comment]
@tinybright 感谢反馈, 问题已解决
