### ISSUE TITLE
项目跑起来的错误

### ISSUE THREAD

**Issue by IT--boy** [goldze/MVVMHabit#4]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:Cannot find the setter for attribute 'binding:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemViewSelector<com.goldze.mvvmhabit.ui.vm.NetWorkItemViewModel> on android.support.v7.widget.RecyclerView.
  file:E:\workspace\workspace_android\studio\MVVMHabit\app\src\main\res\layout\fragment_network.xml
  loc:33:36 - 33:53
  ****\ data binding error ****
直接跑，没任何改动...用的gradle4.1

**Comment by liupeng826** [comment]
Information:Gradle tasks [clean, :app:assembleDebug, :mvvmhabit:assembleDebug]
/Users/v0cn123/Android/AndroidStudio/MVVMHabit/app/src/main/java/com/goldze/mvvmhabit/ui/fragment/NetWorkFragment.java
Error:(7, 40) error: cannot find symbol class FragmentNetworkBinding
Error:(17, 51) error: cannot find symbol class FragmentNetworkBinding
Warning:viewModel.entity.marry is a boxed field but needs to be un-boxed to execute binding:switchState. This may cause NPE so Data Binding will safely unbox it. You can change the expression and explicitly wrap viewModel.entity.marry with safeUnbox() to prevent the warning
/Users/v0cn123/Android/AndroidStudio/MVVMHabit/app/src/main/res/layout/fragment_network.xml
Error:(34, 37) Cannot find the setter for attribute 'binding:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemViewSelector<com.goldze.mvvmhabit.ui.vm.NetWorkItemViewModel> on android.support.v7.widget.RecyclerView. 
Information:BUILD FAILED in 9s
Information:3 errors
Information:1 warning
Information:See complete output in console

我是gradle4.4，也报错

**Comment by goldze** [comment]
已经更新至3.0，重新下载导入即可！
