### ISSUE TITLE
防手抖自定义点击事件报错

### ISSUE THREAD

**Issue by chigang** [goldze/MVVMHabit#46]
android:onClick这个方法没事
但是 binding:onClickCommand老是报错

    
    <TextView
        binding:onClickCommand="@{viewModel.loginOnClickCommand}"
        android:gravity="center"
        android:padding="10dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"

        />
Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'binding:onClickCommand' with parameter type me.goldze.mvvmhabit.binding.command.BindingCommand on android.widget.TextView.
file:E:\MyApplication\app\src\main\res\layout\activity_main.xml
loc:17:34 - 17:62
****\ data binding error ****

**Comment by goldze** [comment]
@chigang 看看是不是你android.support版本没有统一
