### ISSUE TITLE
RecyclerView   item 点击事件

### ISSUE THREAD

**Issue by addappcn** [goldze/MVVMHabit#54]
Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'android:onItemClickCommand' with parameter type me.goldze.mvvmhabit.binding.command.BindingCommand<java.lang.String> on android.support.v7.widget.RecyclerView.
file:D:\work\xiantian\GreenBeans\userapp\src\main\res\layout\activity_quick_order.xml
loc:60:50 - 60:84
****\ data binding error ****

**Comment by goldze** [comment]
绑定的类型错了

**Comment by addappcn** [comment]
?????  请问 哪错了  android:onItemClickCommand  recycleview 不就是这个点击事件吗
