### ISSUE TITLE
MVVMHabit problem for version3.1.3

### ISSUE THREAD

**Issue by qq1275727267** [goldze/MVVMHabit#63]
错误: 无法将类 BindingRecyclerViewAdapters中的方法 setAdapter应用到给定类型;
需要: RecyclerView,ItemBinding<T>,List<T>,BindingRecyclerViewAdapter<T>,ItemIds<? super T>,ViewHolderFactory
找到: RecyclerView,ItemBinding<NetWorkItemViewModel>,ObservableList<NetWorkItemViewModel>,BindingRecyclerViewAdapter<CAP#1>,ItemIds,ViewHolderFactory
原因: 推断类型不符合等式约束条件
推断: CAP#1
等式约束条件: CAP#1,NetWorkItemViewModel
其中, T是类型变量:
T扩展已在方法 <T>setAdapter(RecyclerView,ItemBinding<T>,List<T>,BindingRecyclerViewAdapter<T>,ItemIds<? super T>,ViewHolderFactory)中声明的Object
其中, CAP#1是新类型变量:
CAP#1从?的捕获扩展Object
How should I deal with this problem？

**Comment by WuChen201909** [comment]
可能是Android新版本做了一些改动，这里意思是泛型不匹配，BindingRecyclerViewAdapter需要指定泛型为MultiItemViewModel。
        解决办法是自定义一个Adapter继承BindingRecyclerViewAdapter<MultiItemViewModel>，然后把代码中直接使用BindingRecyclerViewAdapter的位置改为自定义的Adapter。
