### ISSUE TITLE
如何重写覆盖BaseActivity 里面的 showDialog

### ISSUE THREAD

**Issue by huangjinlangzi** [goldze/MVVMHabit#77]
如何重写覆盖BaseActivity 里面的 showDialog

**Comment by ChanKingBooo** [comment]
框架里BaseActivity定义的dialog只是用来显示加载框
你可以直接改他的框架，也可以重新定义一个Dialog，方法还是挺多的

**Comment by goldze** [comment]
@huangjinlangzi 直接在子类里覆盖重写showDialog方法就可以了
