### ISSUE TITLE
Demo可以在补充上功能吗

### ISSUE THREAD

**Issue by rmtic** [goldze/MVVMHabit#8]
已经start，
大神，首先要感谢你，你写的项目给我带来很大的帮助，你是我在github中找到的项目中写的最好的一个，如果Demo能在详细点就好了，对我们这些初学者会带来很大的帮助。
1. 可以增加一个购物车的例子吗？比方产品详情页面中添加或则取消产品时刷行购物车，还有商品详情可以读取和刷新购物数量
2. Recyclerview 例子不是很完整，可以增加分页处理的逻辑吗

**Comment by goldze** [comment]
谢谢你的建议,我会尽量提供更多的例子功能
