### ISSUE TITLE
 binding.setLifecycleOwner(this);

### ISSUE THREAD

**Issue by liguangze** [goldze/MVVMHabit#90]
binding.setLifecycleOwner(this);  这个方法怎么没有了，
      //支持LiveData绑定xml，数据改变，UI自动会更新
        binding.setLifecycleOwner(this);

注释了会不会影响到啥

**Comment by goldze** [comment]
@liguangze 这个不能注释，binding需要和页面生命周期同步，方法找不到应该是你引入版本的问题
