### ISSUE TITLE
is:issue is:open 如果使用你的MVVM框架，我看是增加了大量的代码；框架是为了更好的开发与维护，反而增加了大量代码，不容易开发，不容易维护，适得其反，不要为了设计架构而设计架构

### ISSUE THREAD

**Issue by chenliangj2ee** [goldze/MVVMHabit#94]
如果使用你的MVVM框架，我看是增加了大量的代码；框架是为了更好的开发与维护，反而增加了大量代码，不容易开发，不容易维护，适得其反，不要为了设计架构而设计架构

**Comment by goldze** [comment]
@chenliangj2ee 当你沉淀在应用层开发的时候, 你会感觉业务代码越少越好,  当你已经深入到底层时,  你会发现"地基"有多重要。工具库和框架是两种东西，使用工具库可以减少你的工作，而好的框架不一定会让你的工作量减少，但一定会让你的东西更健壮。这和修房子是一样的道理，使用各种器械工具可以帮助你快速修好房子，但可能会修的东倒西歪。如果使用了好的框架打好地基，按照框架制定的流程完成施工，我相信你修建出来的房子一定更稳固。对于你所说的不容易开发，也许是你对它还不够熟悉；不容易维护，也许是你对MVVM设计模式不够了解。

**Comment by chenliangj2ee** [comment]
你说的不是全无道理，现实情况，是哪个老板不求速成，巴不得明天上线，其次，代码多了，不代表就是健壮，1万行代码出错量大概率的比5千行的多，大部分开发者，都是中低端的，不是大神，修房子，你是修自己家的房子，东西越多越好，如果给你一个10万价格，你修别人的房子，你就不会考虑这么多了，

**Comment by goldze** [comment]
@chenliangj2ee 没有最好的框架，只有最适合自己的框架。对于你给别人做10万的外包项目，你不在乎代码维护，只追求速成上线，那你可以不考虑设计模式，你的项目中可以不用单例、工厂、代理、构建者等，一样可以实现你的业务功能。但我想一个对项目负责任、对团队负责任、对自己负责任的开发者来说，不会这样做。你所说的"大部分开发者，都是中低端的"，我更相信他们愿意通过技术来提升自身的价值。

**Comment by Jinhaihan** [comment]
这个要看业务逻辑，如果一个数据要经常被复用显示，各个页面传来传去（商品、购物车）这种需求，MVVM简直太香了。如果每个页面都是单独的，一次性显示且不常更新的，MVVM就显得麻烦了
所以就如作者所说，选最合适的就好了，没有那种啥场景都非常合适的架子
