### ISSUE TITLE
BaseResponse改为自定义类，生成release包转换有问题

### ISSUE THREAD

**Issue by Eilison** [goldze/MVVMHabit#99]
new DisposableObserver<ResponseJson<InfoVo>>() {
                    @Override
                    public void onNext(ResponseJson<InfoVo> response) {
                        ToastUtils.showLong(BuildConfig.BASE_URL + " | " + response.getStatus() + " | " + response.getMessage());
                        if (response.getStatus() == 200) {
                        }
                    }
}

把BaseResponse改为自定义ResponseJson类（里面字段名称不一致），在release生成apk请求，以上代码中response.getStatus()是为0，并在message为null，应该json转换的时候失败了，奇怪的是，debug是没问题的，这是如何解决？

**Comment by goldze** [comment]
@Eilison 检查一下是否是由于release开启了代码混淆导致的
